package db;
// Generated Oct 18, 2020 9:46:37 PM by Hibernate Tools 4.3.1

import java.io.Serializable;




/**
 * User generated by hbm2java
 */
public class User  implements Serializable {


     private Long id;
     private String nama;
     private String email;
     private String password;

    public User() {
    }

    public User(String nama, String email, String password) {
       this.nama = nama;
       this.email = email;
       this.password = password;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


